export const CART_ACTION_TYPES = {
	SET_CART_OPEN_OR_CLOSE: "SET_CART_OPEN_OR_CLOSE",
	SET_CART_ITEMS: "SET_CART_ITEMS",
	SET_CART_COUNT: "SET_CART_COUNT",
	SET_CART_TOTAL: "SET_CART_TOTAL",
	SET_CART_COUNT_AND_TOTAL: "SET_CART_COUNT_AND_TOTAL",
};
